name: Build and deploy

on:
  push:
    tags:
      - '*'

jobs:
  testcoverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests and collect coverage
        run: npm test
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
  docker:
    needs: testcoverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: intility/keyvaultmanager
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}
          tag: ${{ github.GITHUB_REF }}
          tag_with_latest: true
